$('.one').owlCarousel({
    loop:true,
    autoplay:true,
    autoplayTimeout:1000,
    margin:10,
    nav:true,
    dots:false,
    responsive:{
        0:{
            items:1
        },
        600:{
            items:3
        },
        1000:{
            items:5
        }
    }
})
$('.two').owlCarousel({
    loop:true,
    
    
    mouseDrag:true,
    margin:10,
    nav:false,
    responsive:{
        0:{
            items:1
        },
        600:{
            items:3
        },
        1000:{
            items:5
        }
    }
})